### ISSUE TITLE
NS Evaluation

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#122]
I suppose it has to do with non standar evaluation being used at some point, but I was surprised to see (something that can be simplified to) this:
``` r
library(rray)
myArray <- array((v<-1):4 , c(v,4) )
myArray
#>      [,1] [,2] [,3] [,4]
#> [1,]    1    2    3    4
rm(v)
myRray <- rray((v<-1):4 , c(v,4) )
#> Error in is_null(dim): objeto 'v' no encontrado
```

<sup>Created on 2019-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
The same happens in  dplyr:
``` r
library(dplyr)
#> 
#> Attaching package: 'dplyr'
#> The following objects are masked from 'package:stats':
#> 
#>     filter, lag
#> The following objects are masked from 'package:base':
#> 
#>     intersect, setdiff, setequal, union
iris %>% filter(Petal.Length > (newvar<-6.6) )
#>   Sepal.Length Sepal.Width Petal.Length Petal.Width   Species
#> 1          7.7         3.8          6.7         2.2 virginica
#> 2          7.7         2.6          6.9         2.3 virginica
#> 3          7.7         2.8          6.7         2.0 virginica
newvar
#> Error in eval(expr, envir, enclos): objeto 'newvar' no encontrado
```

<sup>Created on 2019-04-27 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>
but it is kind of expected there

**Comment by DavisVaughan** [comment]
This is just a case of how R lazily executes function arguments. In `rray()`, the `dim` argument is used before `x` is, so it gets evaluated first, meaning that `v` doesn't exist yet. Turn it around and this would work `rray((v):4 , c(v<-1,4) )`. I would not rely on this behavior, except for functions where it has been specifically implemented to work that way (for example `tibble()` let's you use previously named columns to create new columns like `tibble(x = 1, y = x + 2)`). Otherwise, you are relying on something that is subject to change by the developer

**Comment by juangomezduaso** [comment]
Ah yes. Thank you for the extensive explanation
