### ISSUE TITLE
cast_compare() wont work with classed matrices/arrays

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#174]
I wonder if  in vec_cast_compare() it might be better to allow classed objects. No doub it is a corner case, but it might be surprising to users that  the broacasting comparators (and similar broadcasting arith Ops) that work on base arrays and matrices, wont work if they have  a class:

``` r

library(rray)

mat<-matrix(1)
class(mat)<-c("foo")
rray_greater(mat, mat)
#> Error in UseMethod("vec_cast_container", to): no applicable method for 'vec_cast_container' applied to an object of class "foo"
```

<sup>Created on 2019-05-18 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

A solution could be to have a permisive default:
```
vec_cast_container.default <- function(x, to) {
  x
}
```

 doing nothing but returning x instead of error. 
Or, if we consider the class as the "container" to be put, shouldn't it be something like:
```
vec_cast_container.default <- function(x, to) {
  class(x)<- class(to)
  x
}
```
 ?

**Comment by DavisVaughan** [comment]
The idea is that you could extend it yourself with `vec_cast_compare.foo()` and then `vec_cast_compare.foo.default()` and `vec_cast_compare.foo.foo()`

There maybe should be a default method that throws a better error

**Comment by juangomezduaso** [comment]
The scenario  I am thinking of is "rray as a tolkit" (the one where rray functions are used with non rray objects), ie when one  would prefer %b>% over > because of broadcasting.  
The author of a class specialicing arrays who also wanted to use rray broadcasting functions should do the method indeed. But i am thinking more on final users using the goodies of both, rray and the other class. 
But, having said that,  it is probably too rare a scenario to bother with it.

**Comment by DavisVaughan** [comment]
I don't think there is any way to robustly do it with a default method since the class is likely not the only thing that is special about the subclass. It likely has attributes as well that might need to be copied over. `xts` objects, for instance, have a number of attributes that might need to be copied over. They have an `index` attribute for the row names that is tied to the data itself. So if the number of rows change, and `vec_cast_container()` is called, it wouldn't be enough to just attach the old attributes back on. It would likely need to call the xts constructor, which isn't something I prepare for unfortunately.
