### ISSUE TITLE
[<- behavior

### ISSUE THREAD

**Issue by juangomezduaso** [DavisVaughan/rray#71]
[<-()  seems to follow base array conventions instead rray [()  ones:
``` r
library(rray)
x <- rray(
  1:12,
  dim = c(2,3,2),
  dim_names = list(c("r1", "r2"), c("c1","c2","c3"), c("d1", "d2")) 
)
x[1,] <-100
#> Error in x_array[...] <- value: número de subscritos incorretos en matriz
x[,1] <-100
#> Error in x_array[...] <- value: número de subscritos incorretos en matriz
```

<sup>Created on 2019-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1)</sup>

**Comment by DavisVaughan** [comment]
Ah, I see. This will take a bit of work. It's because it eventually attempts to do `x[1,]` on a 3D base R array, which isn't allowed. The `[<-` and `[[<-` methods still need some work. I need to write out exactly what I want them to do.

It does work (at least partially) on 2D objects:

``` r
library(rray)
x <- rray(
  1:6,
  dim = c(2,3),
  dim_names = list(c("r1", "r2"), c("c1","c2","c3")) 
)

x[1,] <-100
x
#> <vctrs_rray<integer>[,3][6]>
#>     c1  c2  c3
#> r1 100 100 100
#> r2   2   4   6

x[,1] <-100
x
#> <vctrs_rray<integer>[,3][6]>
#>     c1  c2  c3
#> r1 100 100 100
#> r2 100   4   6
```

<sup>Created on 2019-04-07 by the [reprex package](https://reprex.tidyverse.org) (v0.2.1.9000)</sup>
